resources:
- name: gcdm
  type: compute.v1.instance
  properties:
    zone: us-central1-c
    machineType: zones/us-central1-c/machineTypes/e2-medium
    disks:
    - deviceName: gcdm
      type: PERSISTENT
      boot: true
      autoDelete: true
      initializeParams:
        sourceImage: projects/debian-cloud/global/images/family/debian-11
    networkInterfaces:
    - network: global/networks/default
      accessConfigs:
      - name: External NAT
        type: ONE_TO_ONE_NAT
